.github/workflows/sanity.yaml, .gitignore, Makefile
Introduce the .github/workflows directory and add a action that ensures
that the codegen (manifests/APIs) are up-to-date and the package
formatting (go fmt/goimports) don't produce a diff.
Update the Makefile's format target and also run the goimports command
against the set of Go packages
=> Introduce a sanity github action check

Makefile, provisioner/k8s/manifests/namespace.yaml, provisioner/k8s/manifests/provisionerclass.yaml, provisioner/k8s/manifests/rbac.yaml, provisioner/k8s/manifests/serviceaccount.yaml
Update the Makefile and add an `install` target that creates the
rukpak-specific resources.
Update the manifests root directory and add manifests for a `rukpak`
namespace and the requisite RBAC.
=> Makefile,manifests: Add skeleton of default rukpak resources

Dockerfile
Update the root Dockerfile and replace the generic `COPY . .` command
with only the files and directories needed to create the provisioner
binar(ies). This should help speed up builds as we're not invalidating
the image layer when we modify a file that doesn't affect the actual
build.
Also update the Dockerfile and ensure we're downloading Go
modules at the beginning of the build stage to help cache dependencies
and decrease over build times over subsequent builds.
=> Dockerfile: Optimize image layers to enable better caching

Dockerfile, Makefile
Update the Makefile and ensure that cgo is disabled for both the
registry+v1 and plain bundle provisioners. Update the Dockerfile to
specify an explicit path to the `k8s` executable to silence the "exec
user process caused: no such file or directory" error message when
running this container image locally.
=> Makefile,Dockerfile: Fix the runtime errors in the rukpak container image

.github/workflows/build.yaml
Update the build GHA workflow and ensure we're caching the Go module
cache between CI runs. This allows us to have quicker overall CI run
times as we avoid having to constantly populate the Go module cache when
building the provisioner binaries in CI.
=> .github/workflow: Ensure we're caching the go module cache

Makefile
Signed-off-by: Daniel Sover <dsover@redhat.com>
Small PR to breakout one install directive into two smaller ones based on each provisioner name. Part of general Makefile cleanup.
=> fix: breakout install directive into seperate ones based on provisioner

provisioner/k8s/manifests/provisionerclass.yaml
Removing this manifest as it appears to be vestigial and prevents installation of the k8s provisioner on cluster.
=> chore: removing provisionerclass.yaml from k8s provisioner

internal/util/util.go, provisioner/k8s/main.go
Introduce a flag to the k8s provisioner binary for configuring the
namespace that's used to house system resources. Add a helper function
that checks whether the provisioner is running in a Pod vs. locally, and
defaults to the Pod's serviceaccount namespace file if present.
=> internal,provisioner: Support configuring the system namespace

internal/storage/storage.go, provisioner/k8s/controllers/bundle_controller.go, provisioner/k8s/controllers/bundleinstance_controller.go, provisioner/k8s/main.go, unpack.Dockerfile
Follow-up to #69 and remove the need to use OLM's cpb tooling to copy Bundle contents from scratch-based bundle container images.
=> k8s: Avoid using OLM's cpb tool for unpacking Bundle contents

internal/storage/storage.go, provisioner/k8s/controllers/bundle_controller.go, provisioner/k8s/controllers/bundleinstance_controller.go, provisioner/k8s/main.go
Differentiate between objects owned by bundles and bundleinstances
=> provisioner/k8s: add owner-kind label

internal/updater/updater.go, provisioner/k8s/controllers/bundle_controller.go
Update the EnsureCondition helper function, and avoid setting the
Bundle's status condition array before checking whether the existing and
new conditions are semantically equal.
=> internal,provisioner: Fix how Bundle status conditions are applied

api/v1alpha1/bundleinstance_types.go, manifests/core.rukpak.io_bundleinstances.yaml
Add a new custom printer column for querying the state of an individual BundleInstance locally.
Example failing Bundle:
```bash
$ k get bundleinstances
NAME       DESIRED BUNDLE     INSTALLED BUNDLE   INSTALL STATE         AGE
olm-crds   olm-v0.20.0-crds   olm-v0.20.0-crds   BundleUnpackPending   13h
```
Example successful Bundle:
```bash
$ k get bundleinstances
NAME       DESIRED BUNDLE     INSTALLED BUNDLE   AGE   INSTALL STATE
olm-crds   olm-v0.20.0-crds   olm-v0.20.0-crds   12h   InstallationSucceeded
```
=> api,manifests: Add an BundleInstance installation state custom column

.github/workflows/test.yaml, Makefile, test/e2e/e2e_suite_test.go, test/e2e/k8s_provisioner_test.go
Introduce a barebones Bundle e2e test to ensure we're covering the basic happy path for plain manifest Bundles.
=> Add basic k8s provisioner Bundle e2e tests

.github/workflows/e2e.yaml, .github/workflows/unit.yaml
Update the test.yaml workflow and split the unit and e2e-kind jobs into
their own workflows. This enables the ability to retest them
independently when we encounter a workflow failure as GHA doesn't
support that use case right now.
=> .github/workflow: Split up the test workflow into individual jobs

provisioner/k8s/controllers/bundle_controller.go
Explicitly set this IfNotPresent image pull policy for the initContainer that pulls down the configured provisioner unpacking container image, and copies the unpack binary to a volume-mounted directory to workaround scratch base images that don't have shells. By default, the Always image pull policy is used when the container image specified in a Pod uses the `:latest` tag, so if a user explicitly overrides that --unpack-image when running the k8s provisioner, we're left with some implicit behavior.
=> k8s: Update the unpack image initContainer to use the IfNotPresent pull policy

Makefile
Update the `kind-cluster` Makefile target and delete the testing kind
cluster if it already exists, then re-create that cluster to ensure
we're not using a potentially stale cluster environment during local/CI
e2e runs.
=> Makefile: Ensure better consistency between e2e runs

test/e2e/e2e_suite_test.go, test/e2e/k8s_provisioner_test.go
Add a simple Bundle e2e test that contains an invalid spec.Image container image that doesn't exist, and ensure the Bundle reports back that underlying Pod's status back to the set of Bundle status conditions. This should help avoid regressing on the fixes that went into #77, where we didn't have an e2e structure in place at the time of that PRs' creation.
=> e2e: Surface invalid Bundle container images back to the Bundle status

.golangci.yaml, internal/updater/updater.go, provisioner/plain-v0/README.md, provisioner/plain-v0/controllers/bundle_controller.go, provisioner/plain-v0/controllers/bundleinstance_controller.go, provisioner/plain-v0/main.go, test/e2e/plain-v0_provisioner_test.go
Update the .golangci.yaml file and introduce a basic importas linter configuration to enforce common package imports (corev1, metav1, etc.) throughout the codebase.
=> ci: Add golangci-lint importas linter configuration

test/e2e/plain-v0_provisioner_test.go
=> e2e: use generateName for bundles to avoid test concurrency issues

Makefile
The `load-image` Makefile target was renamed during the changes needed
to streamline our e2e experience. This target is now named `kind-load`
to match the other kind-* related targets.
=> Makefile: Fix the run target to use the renamed kind-load target as a prequisite

Dockerfile.local, Makefile
Signed-off-by: akihikokuroda <akihikokuroda2020@gmail.com>
Closes #98
Add the docker file for the container build and update Makefile to prebuild the executables before container build.
=> build executables locally and package them in an image

Makefile
Update the e2e target and replace the build-local-container ->
build-container targets to ensure that CI is building the root
Dockerfile and using that throughout CI.
=> Makefile: Update the e2e target to use the build-container as a prereq

Makefile
Small PR that fixes the logic in the Makefile `make kind-cluster` target that deletes existing clusters before creating a new one. The existing cluster was not being removed because the whitespace returned from `wc -l` was causing the equality check to fail. Piping the arguments to `xarg` removes any whitespace and causes the equality to return the right result.
=> fix: kind-cluster target was failing to remove existing cluster 

Makefile
The `ifeq` block in the Makefile controlling access to the `kind` delete call is executed when the Makefile is parsed. This causes the Makefile to take longer to evaluate and it is confusing to see something like "kind: command not found" in the output of an unrelated task.
Before:
```
$ make generate
/bin/sh: kind: command not found
...
```
After:
```
$ make generate
...
```
This PR just forcefully calls `kind delete cluster`, which happily succeeds if the named cluster is non-existent.
=> Makefile: only run 'kind' when necessary

.github/workflows/deploy.yaml, .github/workflows/sanity.yaml
Adding a new action that pushes a new `main` tagged image to our quay repository on a push to `main`. There is a follow-up PR coming that will also do this on `release` which will create a semantically-version tagged image.
*Note* this will continue to fail until we add the required secrets to this repository. I didn't have the permission to do this.
Closes #91
=> ci(deploy): add new workflow for deploying image with main tag

provisioner/plain-v0/manifests/01_cluster_role.yaml, provisioner/plain-v0/manifests/02_role.yaml
Adds * RBAC rules to the provisioner to install combo successfully -- this is part of the documentation work, since in the plain-v0 provisioner docs we use combo as an example bundle to install.
=> fix: add back * RBAC rules to successfully install arbitrary manifests

Makefile
Building the local Dockerfile fails on non-linux machines since no GOOS or GOARCH variables are specificied to make build, which causes execution to fail. For example, building the binaries locally on macOS, then putting them in a `gcr.io/distroless/static:debug` linux based image, we see `standard_init_linux.go:228: exec user process caused: exec format` error on startup. This PR sets the default build GOOS flag to linux when building the container locally.
=> fix: specify linux build flag for make build-local-container

provisioner/plain-v0/README.md
Closes #60 
Provides documentation on the newly introduced plain-v0 provisioner via the provisioner scoped README
=> doc: outline plain-v0 provisioner

Makefile
This PR updates the default name of the kind cluster being used so that non-e2e targets can succeed. Currently  `make run` expects there to be a kind cluster named "rukpak-e2e" to be available, which is unexpected. This is due to the `kind-load` target referencing the cluster name. By changing the default name of the expected cluster to kind, but still preserving the rukpak-e2e cluster name for the `make e2e` target specifically, we give users a more intuitive local experience while preserving the hermetic e2e workflow.
=> fix: use default kind cluster name

go.mod, internal/helm-operator-plugins/predicate/depedent_test.go
Signed-off-by: akihikokuroda <akihikokuroda2020@gmail.com>
Add unit tests for internal/helm-operator-plugins/predicate/dependent.go
=> add internal/helm-operator-plugins/dependent.go unit tests

provisioner/plain-v0/controllers/bundle_controller.go, provisioner/plain-v0/controllers/bundleinstance_controller.go
Fixing the RBAC markers to point to the appropriate new `core.rukpak.io` api group.
Closes #128
=> fix(plain-v0): update RBAC generation markers

Dockerfile.local, Makefile
This PR changes the `make build` target to name the binary with a GOOS suffix to indicate that the binary is for linux systems when `make build-local-container` is ran. This change does not affect the binary name when building locally via `make build` and GOOS is not set.
=> add optional GOOS tag to built binaries to specify linux build for build-local-container

Dockerfile, Makefile, cmd/unpack/main.go, internal/version/version.go, provisioner/plain-v0/main.go
This PR cleans up the Makefile to make it more consistent, and adds a version flag to the binaries that are produced in rukpak: the unpack binary and the plain-v0-provisioner binary. This version information will be helpful as development accelerates and encoding version information in the binary will be useful when debugging. 
```
$ ./bin/plain-v0 --version
Git commit: ba0e6da94d140e7e8b2780bc4f9a541d7f2ccdc8
```
=> add version information to rukpak built binaries

provisioner/plain-v0/README.md
Adding a small note about the behavior of the plain-v0 provisioner when multiple BundleInstances reference the same Bundle.
=> docs(plain-v0): add note about behavior for BI's with same Bundle referenced

api/v1alpha1/bundleinstance_types.go, internal/provisioner/plain/controllers/bundleinstance_controller.go, test/e2e/plain_provisioner_test.go
Adding changes that improve the UX around BundleInstances that reference a delete Bundle. Originally, a BundleInstance with an underlying Bundle that was deleted would emit a "BundleLookupFailed" reason for the "Install" condition. Now there is a "HasValidBundle" condition that is emitted on this event and the original "InstallSucceeded" condition along with it.
Should we have a follow-up PR that adds a printer column to track the state of the "HasValidBundle"?
Closes #129
=> feat(plain): improve user-experience around BundleInstances that reference a deleted Bundle

api/v1alpha1/bundle_types.go, api/v1alpha1/bundleinstance_types.go, manifests/core.rukpak.io_bundleinstances.yaml, manifests/core.rukpak.io_bundles.yaml
I believe the **BundleSpec** and **BundleInstanceSpec** should be required.
=> make bundlespec and bundleinstancespec required

internal/provisioner/plain/controllers/bundle_controller.go
The default image pull policy is IfNotPresent for a container image unless the container image tag is set to 'latest' or the tag is unset (e.g. ""), so we should infer the pull policy from the user-provided container image.
=> plain: Infer the ImagePullPolicy from the Bundle's spec.Image tag

internal/provisioner/plain/controllers/bundle_controller.go
This check ensures that in the case where no objects where unpacked as a result of the unpack pod a failure status will propagate to the Bundle. 
This prevents the case where zero objects are stored successfully and the Bundle is considered Unpacked even though no content was persisted to the cluster.
=> add unpacked object length check 

Makefile, cmd/unpack/main.go, internal/provisioner/plain/controllers/bundle_controller.go, test/e2e/plain_provisioner_test.go, testdata/bundles/plain-v0/empty/Dockerfile
With this change, we can now unpack the image at the root of the image
filesystem, making unpack capable of handling future bundle formats that
may include other files and directories outside of /manifests
This PR also adds a test to ensure that we correctly fail bundles that
contain no manifests
=> make unpack ignore irrelevant root directories

Makefile, cmd/unpack/main.go, go.mod, go.sum, internal/provisioner/plain/controllers/bundle_controller.go, test/e2e/plain_provisioner_test.go, testdata/bundles/plain-v0/no-manifests/.dockerignore, testdata/bundles/plain-v0/no-manifests/Dockerfile, testdata/bundles/plain-v0/no-manifests/manifests/.gitignore
This commit enables the unpack binary to correctly handle empty
directories, and to encode other filesystem metadata (e.g. file mode).
Closes #175 
=> unpack: encode bundle content in JSON as tar.gz

Makefile
This PR adds a `TEST` variable that allows to easily focus on a specific e2e case. 
```
$ TEST='a valid Bundle referencing a remote container image is created' make test-e2e
cd hack/tools; go build -tags=tools -o bin/ginkgo github.com/onsi/ginkgo/v2/ginkgo
/Users/dsover/code/src/rukpak/hack/tools/bin/ginkgo -v -trace -progress -focus "a valid Bundle referencing a remote container image is created" test/e2e
```
=> Add focus flag to e2e test target

docs/plain-bundle-spec.md, internal/provisioner/plain/README.md
Closes #75 .
Additional metadata (as discussed in #23) is being treated as optional in the current plain+v0 spec, since there are no provisioner specific requirements around metadata at this time. This spec omits metadata until we agree on a specified metadata format and the benefits of requiring such a format.
=> doc: add plain+v0 bundle spec

test/e2e/webhook_test.go
Add simple tests for bundle name length check.
Closes #189
=> add validating webhook e2e test

Makefile
When using the target `install` on a plain kind cluster, I ran into the
following error:
```
validatingwebhookconfiguration.admissionregistration.k8s.io/rukpak-webhook created
unable to recognize "manifests/bundle-webhook/07_webhook.yaml": no matches for kind
"Certificate" in version "cert-manager.io/v1"
unable to recognize "manifests/bundle-webhook/07_webhook.yaml": no matches for kind
"Issuer" in version "cert-manager.io/v1"
```
Looks like the cert-manager needs to be installed on cluster to support PR #156
This PR includes the installation of the cert-manager to the `install` target.
=> Makefile: Include cert-manager installation on `install`

internal/git/git.go, internal/git/git_test.go, internal/provisioner/plain/controllers/bundle_controller.go
I was debugging the git source flake and I noticed that the log output
for the unpack pod was unexpectedly long. Turns out, the "contents" JSON
included the full filesystem of that container, which includes a few large
binaries. All we actually need is the bundle directory.
This commit resolves this with a few tweaks:
- Change the volume mount from "/manifests" to "/bundle".
- Just before copying, delete the repo's ".git" directory. This avoids
copying that directory into /bundle when we're treating the entire git
repository as the bundle.
- Copy the entire specified directory within the git repo into the
/bundle directory (this results in "/bundle/manifests" for valid
bundles.
- The unpack binary unpacks the "/bundle" directory rather than "/"
I'm not sure if this is the root cause of …
=> git bundle source: avoid copying full contents of unpack container

api/v1alpha1/bundle_types.go, manifests/core.rukpak.io_bundles.yaml
Purely exploratory right now but this seemed like it was a nice addition in my eyes when managing multiple Bundles locally:
```console
$ k get bundles
NAME           IMAGE                                           TYPE    PHASE       AGE
combo                                                          git     Failing     17m
combo-v0.0.1   quay.io/tflannag/bundle:combo-operator-v0.0.1   image   Unpacking   6s
```
We'll still have the problem around the IMAGE custom column (tracked in #163) but I think we can work around that limitation in parallel.
=> api,manifests: Introduce a 'Type' custom column to the Bundle CRD

Makefile, internal/provisioner/plain/controllers/bundle_controller.go, test/e2e/plain_provisioner_test.go, testdata/bundles/plain-v0/subdir/.dockerignore, testdata/bundles/plain-v0/subdir/Dockerfile, testdata/bundles/plain-v0/subdir/manifests/emptydir/.gitignore, testdata/bundles/plain-v0/subdir/manifests/namespace-a.yaml, testdata/bundles/plain-v0/subdir/manifests/subdir/namespace-b.yaml
Add a new bundle that has subdirectories in the manifests directory.  The yaml files in the subdirectory should be ignored.
Closes #195
=> make sure nested manifest directories don't cause any affects

Makefile, test/e2e/plain_provisioner_test.go, testdata/bundles/plain-v0/invalid-crds-and-crs/Dockerfile, testdata/bundles/plain-v0/invalid-crds-and-crs/manifests/resources.yaml
Introduce a new BI e2e test that's responsible for stamping out a Bundle that contains CRD definitions and instances of those CRDs and ensuring that the install eventually reports a failed status.
Closes #185
Related to #131 
=> e2e: Ensure that Bundles that contain CRDs and instances of those CRDs fail

internal/util/util.go, test/e2e/e2e_suite_test.go, test/e2e/plain_provisioner_test.go
Introduce a new top-level describe for ensuring that the underlying resources used by the Bundle/BI controllers are properly garbage collected once those resources are deleted from the cluster.
Closes #188
=> e2e: Add test cases for BI/Bundle garbage collection

test/e2e/plain_provisioner_test.go
Update the Logf helper function which wraps the GinkgoWriter() utility and automatically inject a newline escape character when the input string doesn't already contain that.
=> e2e: Automatically inject a newline escape character in the Logf function

docs/git-bundles.md, docs/plain-bundle-spec.md
This PR adds additional documentation for bundles with custom bundle directory roots.
=> (doc): git-based bundles with custom directory specified 

internal/git/git.go, internal/git/git_test.go, test/e2e/plain_provisioner_test.go
This commit copies the _contents_ of the bundle directory into `/bundle` rather than the specified bundle directory itself.
This resolves an issue where if `spec.source.git.directory` specified `path/to/root` (where `path/to/root` contains a `manifests` directory at `path/to/root/manifests`, the unpacked `/bundle` directory would contain `/bundle/root/manifests`, when it should contain `/bundle/manifests`.
I introduced this bug in #211 as part of those fixes.
=> internal/git/git.go: fix copying of bundle root

docs/git-bundles.md
Makes the git-based bundles document more generic with respect to plain+v0 bundles ~and fixes the provided example for a bundle with custom directories to match the current implementation.~
=> (doc): follow-up to git-based bundles doc

.goreleaser.yml, Makefile
Avoid hardcoding the env.IMAGE_REPO in the goreleaser configuration as we can infer that information from the Makefile when running the release target. Add support for overriding the IMAGE_REPO and IMAGE_TAG variables.
=> Makefile: Add support for overriding the IMAGE_* variables locally

.goreleaser.yml, Dockerfile, Makefile, cmd/crdvalidator/handlers/crd.go, cmd/crdvalidator/main.go, internal/crd/crd.go, internal/util/name.go, manifests/crdvalidator/00_namespace.yaml, manifests/crdvalidator/01_cluster_role.yaml, manifests/crdvalidator/01_service_account.yaml, manifests/crdvalidator/02_cluster_role_binding.yaml, manifests/crdvalidator/03_service.yaml, manifests/crdvalidator/04_webhook.yaml, manifests/crdvalidator/05_deployment.yaml, manifests/crdvalidator/kustomization.yml, test/e2e/crdvalidator_test.go
_NOTES_ 
- This is an alternative approach to #199
- Adding a few E2E test cases for this logic
- This webhook is intended to eventually live in its own repository separate from RukPak components. The implementation has been done with that in mind.
Doing a few things here that we should talk through:
- Creating a new webhook (`crdvalidator`) under the `cmd` directory. There has been talk of moving this webhook into its own repo in the future and this should make that very easy.
- Adding Makefile targets to deploy the webhook
- Moving the `crd` util package along side the webhook code.
- Should this have an option to force `crd` applies through or would that option just be removing this webhook?
=> feat(crdvalidator): adding webhook to ensure safety of crd create/upgrades

test/e2e/crdvalidator_test.go
Adding a new test case to the `crdvalidator` e2e suite that prevents a schema update from breaking an existing CR.
=> test(crdvalidator): add e2e test case for a crd update that breaks an existing cr

internal/crd/crd_test.go, internal/util/kubestructs.go, test/e2e/crdvalidator_test.go, test/testutil/constants.go, test/testutil/name.go, test/testutil/structs.go
In addition I am moving the `NewTestingCRD` function into a new `testutil` package in `test` along side a new function called `NewTestingCR` to streamline the creation of these resources.
=> test(crdvalidator): add unit testing for underlying crd validation package

Makefile, manifests/provisioners/kustomization.yaml
Update the manifests/provisioner directory structure and add a base kustomization.yaml that only points to the plain provisioner kustomization right now. This allows people to run `kustomize build manifests/provisioners` locally without having to specify the manifests/provisioners/plain directory, which makes it easier to script around when generating release artifacts.
=> manifests: Add a base kustomization.yaml for the set of provisioner manifests

.github/workflows/release.yaml, Makefile
#187 broke the release workflow where automation was responsible for creating a new github release when a new tag was pushed to this repository.
Closes #261
=> .github: Fix the release workflow automation on tag event triggers

Makefile, manifests/kustomization.yaml
This enables `kustomize build ./manifests | kubectl apply -f -` to install all of rukpak in a single command
It also means we are able to consolidate our makefile targets for installation down to a single `install` target.
=> Add base kustomization.yaml to manifests directory

api/v1alpha1/bundle_types.go, internal/provisioner/plain/controllers/bundle_controller.go, manifests/apis/crds/core.rukpak.io_bundles.yaml
An optional `ImagePullSecretName` is added in the `ImageSource`.
Closes: #81
=> add image pull secret suport for image bundle

api/v1alpha1/bundle_types.go, manifests/apis/crds/core.rukpak.io_bundles.yaml
This PR is a bandaid solution to #163 which renames the displayed field from `Image` to `Reference` and moves it behind the `-o wide` output. It does not successfully display an arbitrary reference to an image or git repository, as JSONPath does not support conditional statements and there is no singular field to reference. Potentially once #164 merges there can be a follow-up that links `Reference` to a well-defined field on the Bundle status. 
Closes #163 
There will be a follow-up issue to move the displayed field back to the default output, instead of under `-o wide`.
=> Generalize bundle image printcolumn

internal/provisioner/plain/controllers/bundle_controller.go, internal/provisioner/plain/controllers/bundleinstance_controller.go, internal/provisioner/plain/types/types.go, internal/updater/updater_test.go, test/e2e/plain_provisioner_test.go, test/e2e/webhook_test.go
Introduce a types.go package that contains the constant variables used throughout the plain provisioner implementation. Update references to that plain provisioner unique ID to point to that consistent constant variable vs. scattering this information across the repository.
=> internal,test: Add a package that contains the unique provisioner IDs

internal/provisioner/plain/controllers/bundleinstance_controller.go, test/e2e/plain_provisioner_test.go
Modifies bundleinstance_controller to include human readable message in
message field after successful installation of a BundleInstance
resource.
Modifies associated tests to represent that change.
=> FIX: human readable BundeInstance success messages

README.md, cmd/crdvalidator/README.md, cmd/crdvalidator/annotation/annotation.go, cmd/crdvalidator/handlers/crd.go, manifests/crdvalidator/04_webhook.yaml, test/e2e/crdvalidator_test.go
The intent of this PR is to give an opt-out approach for the `crdvalidator` which only runs against RukPak provisioned CRDs. `crdvalidator` will now check the `Labels` of an incoming CRD event for `core.rukpak.io/owner-kind` to determine if it is being created by RukPak and thus run the validation logic. To turn this off for a specific CRD made by RukPak, the following annotation needs to be set for the CRD within the `Bundle`:
```yaml
core.rukpak.io/safe-upgrade-validation: disabled
```
Closes #245 
Closes #259
=> Optional CRD Validation

.golangci.yaml, cmd/crdvalidator/handlers/crd.go, internal/crd/crd_test.go, internal/storage/storage_test.go, internal/updater/updater_test.go, internal/util/util.go, test/e2e/crdvalidator_test.go, test/e2e/e2e_suite_test.go, test/e2e/webhook_test.go
Update the golangci-lint configuration file, and add a linter configuration for the [goimports](https://golangci-lint.run/usage/linters/#goimports) linter to enforce package import grouping.
=> Add a goimports linter configuration to enforce package import structure

api/v1alpha1/bundleinstance_types.go, manifests/apis/crds/core.rukpak.io_bundleinstances.yaml
Update the kubebuilder markers for the BI types.go definition and add a shortName configuration that allows users to interact with bundleinstance resources locally without typing out the full name.
=> api,manifests: Add a short name for the BundleInstance API

README.md
This PR adds an installation section to the top-level README so new users of the project can at a glance see how to quickly install RukPak. Additional discussion around this in #312.
Closes #312
=> Add install section to the root-level README

.github/workflows/sanity.yaml, README.md, cmd/crdvalidator/README.md
This PR introduces a new GH Action specifically for linting the markdown files in the repository. It relies on the https://github.com/github/super-linter project which seems to be the most maintained GH Action for linting and specifically for markdown. It only lints markdown files and does not use any of the other linters included, since golangci-lint is used for Go code in the project.
=> Add markdown linter GH Action

api/v1alpha1/bundle_types.go, internal/provisioner/plain/controllers/bundle_controller.go, internal/provisioner/plain/main.go, internal/storage/localdir.go, internal/storage/localdir_test.go, internal/storage/storage.go, internal/updater/updater.go, internal/updater/updater_test.go, manifests/apis/crds/core.rukpak.io_bundles.yaml, manifests/provisioners/plain/kustomization.yaml, manifests/provisioners/plain/resources/bundle_reader_client_clusterrole.yaml, manifests/provisioners/plain/resources/cluster_role.yaml, manifests/provisioners/plain/resources/deployment.yaml, manifests/provisioners/plain/resources/service.yaml, test/e2e/plain_provisioner_test.go
This PR works toward closing #311.
It does several things:
1. Adds a new `status.contentURL` to the Bundle API
1. Updates the storage interface to include an HTTP handler to serve bundle content
1. Updates the storage interface to allow a provisioner to get a URL for a bundle
1. Updates the `LocalDirectory` storage implementation to implement 2 and 3
1. Updates the `LocalDirectory` storage implementation to use bundle name rather than bundle UID for better UX (both are unique to bundles throughout the cluster since bundles are cluster-scoped)
1. Updates the plain provisioner to register the storage HTTP handler on the existing controller-runtime webserver, under the `/bundles` path.
1. Updates the plain provisioner to populate the `status.contentURL` field when bundles are successfully …
=> Add support for serving bundle content

manifests/provisioners/plain/resources/deployment.yaml
Update the plain provisioner deployment manifest and add the [`kubectl.kubernetes.io/default-logs-container` annotation](https://github.com/kubernetes/kubernetes/pull/87809) so there's no need to specify the container (-c) flag when interacting with kubectl log commands.
=> manifests: Add the default logs container annotation for the plain provisioner deployment

README.md
The badge is expected for open-source Go projects and adds some flair to the README
=> Add go report card badge to README

Makefile
Add checks to ensure that the deployments bundled with the default
rukpak installations are Available before returning from install. This
prevents users accidentally creating rukpak resources before the
controllers are initialized.
This does hardcode the namespace/name of the deployments, but since we don't currently provide a way to configure those it seems like an acceptable compromise.
=> Add condition checks to install target

.github/workflows/release.yaml, .gitignore, .goreleaser.template.yml, Makefile
Automate the process of generating and attaching the rukpak.yaml release manifests that reference the container image tags built by goreleaser.
- Add the `quickstart` target that's responsible for building the set of kustomize manifests in this repository, and substituting the default `quay.io/operator-framework/rukpak:latest` container image tag with the current image tags.
- Ensure the release GHA workflow now calls this `quickstart` Makefile target during tag event triggers
- Update the goreleaser template configuration file, and add a `extra_files` field in the release pipeline that attaches the rukpak.yaml file as an artifact.
- Ignore the generated rukpak.yaml release manifests locally.
- Closes #337 
- Related to #210 
- See …
=> ci: Automate the process of generating the rukpak release manifests

.goreleaser.template.yml, Makefile
Update the goreleaser template configuration file, and add a header field for injecting the installation instructions. The current release's tag will be substituted at runtime.
- Related to #337
- Related to #210
- See https://github.com/timflannagan/rukpak/releases/tag/v0.3.2 where I ran these changes against my fork
=> Add an installation header to the goreleaser configuration

internal/provisioner/plain/main.go, manifests/provisioners/plain/resources/deployment.yaml
Add support for overriding the default plain provisioner storage directory so developing locally via `go run internal/provisioners/plain/main.go` works.
=> internal: Add support for configuring the Bundle content storage directory

internal/provisioner/plain/controllers/bundleinstance_controller.go, internal/util/util_test.go
Fixes a duplicate package import and removes a function that is no
longer being used.
These issues were found by simply running `golangci-lint run` locally -- doesn't look like our remote CI didn't pick these up, or at least causes a failure in that case.
=> Fix lint issues found from golangci-lint run

README.md, docs/provisioner-spec.md, internal/provisioner/plain/README.md
One of the follow-ups for #311 was to document the new `status.contentURL` field, provide an example for how a client could view the content of a bundle by fetching that URL, and to describe the expectations for provisioner implementations with respect to this field.
This PR:
- updates the plain provisioner doc to include a concrete example of fetching the bundle data
- adds a draft provisioner spec that documents most of the things we (currently) expect a provisioner to do.
=> docs: provisioner specs and usage of contentURL

.github/workflows/sanity.yaml
Update the lint GHA workflow job to use the lint Makefile target to ensure that both local/CI environments use the same entrypoint and version of golangci-lint. Add a step that caches the build and module paths to cut down on the overall runtime when running the lint job.
Separate the step responsible for linting the markdown files in the repository from lint job, into it's own job so that it can run in parallel with the other jobs defined in the sanity workflow.
=> .github: Refactor the sanity workflow

Makefile
Adds an uninstall target to conveniently remove rukpak from the cluster
entirely. Relies on the kustomize output to build a list of objects to
remove.
<details>
```
rukpak(main): kustomize build manifests | kubectl delete -f -
namespace "crdvalidator-system" deleted
namespace "rukpak-system" deleted
customresourcedefinition.apiextensions.k8s.io "bundleinstances.core.rukpak.io" deleted
customresourcedefinition.apiextensions.k8s.io "bundles.core.rukpak.io" deleted
serviceaccount "crd-validation-webhook" deleted
serviceaccount "plain-provisioner-admin" deleted
serviceaccount "rukpak-core-admin" deleted
clusterrole.rbac.authorization.k8s.io "bundle-reader" deleted
clusterrole.rbac.authorization.k8s.io "crd-validation-webhook" deleted
clusterrole.rbac.authorization.k8s.io …
```
=> Add uninstall target

Makefile, hack/tools/go.mod, hack/tools/go.sum, hack/tools/tools.go
Follow-up to #357 which uses kubectl's kustomize command to manage our kustomize manifests.
Refactor any Makefile targets that rely on kustomize with kubectl commands:
- Update the install Makefile command and replace `kustomize build` with `kubectl apply -k manifests`.
- Update the quickstart Makefile command to use `kubectl create --dry-run` and pipe that output to sed.
=> hack,Makefile: Remove kustomize as a direct tool dependency

docs/git-bundles.md
Code is delayed.  Removing the private git support descriptions added in #325
=> remove private git description

Makefile, go.mod, go.sum
- Closes #365
- Update the hack/tools/go.mod and add the github.com/kubernetes-sigs/kind
as a tooling dependency.
- Creates kind endpoint in Makefile to allow installation for
testing/hack purposes.
=>  Add the kind binary to the hack/tools go module

Makefile
- Changes hack/tools kind directory from $(abspath $(TOOLS_BIN_DIR)/KIND)
to $(abspath $(TOOLS_BIN_DIR)/kind).
=> FIX: Fixes mis-capitalization of kind in makefile hack/tools

.github/workflows/e2e.yaml, Makefile, README.md, test/e2e/crdvalidator_test.go
Signed-off-by: Tyler Slaton <tyslaton@redhat.com>
Updating the UX of utilizing `kind` locally to be more seamless. 
The UX goes from:
```
make kind
make kind-cluster
make run
```
to
```
make kind-cluster
make run
```
Additionally, you can change which binary you're using (your own personal, the repo's, etc) by specifying the KIND variable.
```
make kind-cluster KIND=/usr/local/bin/kind
make run
```
Lastly, this PR also updates the `e2e` CI job to benefit from this change.
A follow-up PR will be responsible for updating the docs to reflect this, found in #373.
=> feat(makefile): update installation UX for Kind to be more seamless

internal/provisioner/plain/README.md
The [Installing the Combo Operator](https://github.com/operator-framework/rukpak/tree/main/internal/provisioner/plain#installing-the-combo-operator) instructions referenced broken images. This PR updates those references to the correct images.
Closes: https://github.com/operator-framework/rukpak/issues/251
Cleaner version of [this PR](https://github.com/operator-framework/rukpak/pull/373).
=> Fix the Combo Operator Installation docs

internal/provisioner/plain/controllers/bundleinstance_controller.go, internal/util/hash.go, internal/util/labels.go, internal/util/util.go, internal/util/util_test.go, test/e2e/plain_provisioner_test.go
Adds a unique hash label to the metadata of embedded bundles in the BI spec. The hash label is called `core.rukpak.io/bundle-template-hash` and the value is the fnv32a hash of the bundle template upon creation. 
Closes #334
=> Add unique hash label to dynamic Bundle metadata

internal/provisioner/plain/controllers/bundle_controller.go, internal/provisioner/plain/main.go, internal/storage/http.go, internal/storage/http_test.go, internal/storage/localdir_test.go, internal/storage/storage.go, internal/storage/storage_test.go, manifests/provisioners/plain/resources/cluster_role.yaml
When multiple provisioners exist, it will be possible for a bundle instance with provisioner class name "foo" to embed a bundle with provisioner class name "bar". In this case, the "foo" bundle instance provisioner will need to be able to load the bundle content of the "bar" bundle, whose storage is handled by another provisioner.
This PR enables the "foo" provisioner to fallback to loading a bundle via its `status.contentURL` if it experiences an error loading that bundle from its storage.
=> Add HTTP storage Loader to enable loading of other provisioner's bundles

api/v1alpha1/bundle_types.go, api/v1alpha1/bundle_webhook.go, internal/provisioner/plain/controllers/bundle_controller.go, internal/util/util.go
Add a controller event handler implementation that maps events to reconciliation requests for owned objects that have the expected provisionerClassName field. 
This is used in place of the generic `handler.EnqueueRequestForOwner` implementation because it additionally considers the owner's provisioner class name. This extra consideration is important when multiple provisioners exist in a cluster and it is necessary for them to ignore events for owned objects that reference a bundle that is assigned to another provisioner class.
Reviewer note: I implemented the `MapOwneeToOwnerProvisionerHandler` function such that it would be trivial to use it for BundleInstance in the future if that need ever arises.
@timflannagan mentioned that while this approach does work, it _is_ fairly complex to …
=> consider provisioner ID before enqueuing requests for bundles

internal/provisioner/plain/README.md
The names of embedded Bundles have recently been modified to include the
hash of the template as part of the name. This means the names of the
Bundles are now deterministic. This PR updates the documentation to
reflect the new content-addressable Bundle name in the examples.
=> docs: Update plain Bundle names to include new content based hash

internal/source/git.go
This is a part of #408 
The clone progress of gitsource is put into log only on error
=> put clone progress into log only on error

Makefile, tools/imageregistry/bundle_local_image.yaml, tools/imageregistry/daemonset.yaml, tools/imageregistry/load_test_image.sh, tools/imageregistry/nerdctl.yaml, tools/imageregistry/registry.yaml, tools/imageregistry/service.yaml, tools/imageregistry/setup_imageregistry.sh, tools/imageregistry/sniff.sh
The registry pod is setup in `rukpak-system` namespace in the kind cluster
Self-signed certificate is generated and ca certificates is set to necessary places
The registry can be accessed by `docker-registry:$NODE_PORT` from the host system and by `docker-registry:5000` in the cluster.  The credential for the registry is `myuser/mypasswd`.  The `registrysecret` secret is created for the image pull secret.
e2e tests are not updated or added in the PR.
Closes #280 
=> setup in-cluster image registry

internal/provisioner/README.md, internal/provisioner/plain/README.md, internal/provisioner/registry/README.md
Doing two things here:
1. Aggregating some document concepts that can be shared in the root `provisioner` README.
2. Filling out the `registry` provisioner's README.
=> docs: update provisioner docs to contain information about registry+v1 and aggregate concepts

.golangci.yaml, cmd/crdvalidator/handlers/crd.go, cmd/crdvalidator/main.go, cmd/unpack/main.go, internal/convert/registryv1.go, internal/crd/crd.go, internal/provisioner/plain/controllers/bundle_controller.go, internal/provisioner/plain/controllers/bundleinstance_controller.go, internal/provisioner/registry/controllers/bundle_controller.go, internal/source/git.go, internal/source/image.go, internal/storage/localdir.go, internal/unit/unit.go, internal/updater/bundle-instance/updater_suite_test.go, internal/updater/bundle/updater_suite_test.go, internal/util/util.go
Disabling `errorlint`'s configuration that enforces all errors to be wrapped. Motivation: https://go.dev/blog/go1.13-errors#whether-to-wrap
Also adding some new, seemingly low-impact linters:
- bodyclose - checks whether HTTP response body is closed successfully
- misspell - Finds commonly misspelled English words in comments
- nonamedreturns - Reports all named returns (see discussion [here](https://github.com/operator-framework/rukpak/pull/407#discussion_r887182505))
- unused - Checks Go code for unused constants, variables, functions and types
- varcheck - Finds unused global variables and constants
=> enable more linters; disable required error wrapping

api/v1alpha1/bundledeployment_types.go, internal/provisioner/plain/README.md, internal/provisioner/registry/README.md, internal/updater/bundle-deployment/updater.go, internal/updater/bundle-deployment/updater_test.go, manifests/apis/crds/core.rukpak.io_bundledeployments.yaml, test/e2e/plain_provisioner_test.go, test/e2e/registry_provisioner_test.go
This change simplifies the BI status and improves the UX in the world
of dynamic bundles, when the bundle is known when creating the BI.
Closes #403 -- see #331 for more context.
=> api: Change BundleInstance status.installedBundleName to status.activeBundle

test/e2e/plain_provisioner_test.go
Closes #415 
This PR has one additional test that accesses to a private git repository via https scheme.  The following environment variables must be set to enable and execute the test
```
PRIVATE_REPO
PRIVATE_REPO_USERNAME
PRIVATE_REPO_PASSWORD
```
example values for `https://github.com/akihikokuroda/private` repository are:
```
PRIVATE_REPO=https://github.com/akihikokuroda/private
PRIVATE_REPO_USERNAME=akihikokuroda
PRIVATE_REPO_PASSWORD=mypassword
```
=> e2e test private git repository

internal/provisioner/README.md
Kubernetes 1.24 doesn't have `secrets` in serviceaccount.  
This change requires 
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/
amd64"}
```
=> kubernetes 1.24 service account token secret change

internal/provisioner/plain/controllers/bundledeployment_controller.go
Closes #444 
BundleDeployment condition has this with this PR.
```
conditions:
- lastTransitionTime: "2022-07-08T16:37:24Z"
message: 'Failed to unpack the Bundle: fail-6f96958c8b, reason: get objects
from bundle manifests: read ".gitignore": error unmarshaling JSON: while decoding
JSON: json: cannot unmarshal string into Go value of type map[string]interface
{}'
reason: UnpackFailed
status: "False"
type: HasValidBundle
```
for the Bundle condition
```
conditions:
- lastTransitionTime: "2022-07-08T16:37:24Z"
message: 'get objects from bundle manifests: read ".gitignore": error unmarshaling
JSON: while decoding JSON: json: cannot unmarshal string into Go value of
type map[string]interface {}'
reason: UnpackFailed
status: "False"
type: …
```
=> include bundle unpack failure msg in the bundledeployment condition msg 

internal/source/local.go
Wrapping this call in a retry is not the best way to handle a conflict
error. It can be instead propagated back up and retried.
=> source: remove TODO comment regarding retrying updates

docs/hackmd-notes.md
Adds a section to the docs with links to all the hackmd documents on the RukPak team. Since there is no way to link to the team repository via HackMD, links to individual files are provided instead. 
This document should be kept up to date -- as new designs are written in HackMD, this document should be updated to add a link to the new design. 
Closes #441
=> docs: add hackmd links

CONTRIBUTING.md, README.md
Follow up to #469.
Adds a link to the hackmd notes in the CONTRIBUTING.MD file.
Adds a small section on documentation to the root-level README.
=> docs: add new sections

cmd/rukpakctl/cmd/bundle.go, cmd/rukpakctl/cmd/bundledeployment.go, cmd/rukpakctl/cmd/content.go, cmd/rukpakctl/cmd/create.go, cmd/rukpakctl/cmd/root.go, cmd/rukpakctl/main.go, cmd/rukpakctl/utils/utils.go, internal/provisioner/plain/controllers/bundle_controller.go, internal/provisioner/plain/controllers/bundledeployment_controller.go, internal/provisioner/registry/controllers/bundle_controller.go, internal/util/util.go
This is step 1 of making some improvements discussed in #464, which is a minor refactoring of the rukpakctl commands to remove global vars and unnecessarily exported types.
I also uncovered a few places we should be passing contexts down, so I've made those fixes as well.
Step 2 will follow up with further changes, to include:
- renaming `local` to `configmaps`
- supporting multiple configmap references which include their directory paths within bundle
- forcing the configmap references to be in the rukpak-system namespace (that way bundle controllers don't have to cache all configmaps on the cluster)
=> rukpakctl: remove use of globals and exported types; use contexts consistently

test/e2e/api_validation_test.go, test/e2e/webhook_test.go
Closes #435 
Create a new test file api_validation_test.go.  Added some tests and moved some tests from webhook_test.go
=> api validation tests

api/v1alpha1/bundle_types.go, api/v1alpha1/bundledeployment_types.go, manifests/apis/crds/core.rukpak.io_bundledeployments.yaml, manifests/apis/crds/core.rukpak.io_bundles.yaml, test/e2e/plain_provisioner_test.go
This PR add validation for the provisoner class name. 
- contain only lowercase alphanumeric characters, '/' or '.'
- start with an alphabetic character
- end with an alphanumeric character
=> provisioner class name validation

README.md, api/v1alpha1/bundle_types.go, api/v1alpha1/bundledeployment_types.go, cmd/rukpakctl/cmd/bundle.go, cmd/rukpakctl/cmd/bundledeployment.go, cmd/rukpakctl/cmd/run.go, docs/bundle-immutability.md, docs/git-bundles.md, docs/local-bundles.md, docs/plain-bundle-spec.md, docs/provisioner-spec.md, docs/uploading-bundles.md, internal/provisioner/helm/README.md, internal/provisioner/helm/types/types.go, internal/provisioner/plain/README.md, internal/provisioner/plain/types/types.go, internal/provisioner/registry/README.md, internal/provisioner/registry/types/types.go, manifests/apis/crds/core.rukpak.io_bundledeployments.yaml, manifests/apis/crds/core.rukpak.io_bundles.yaml, test/e2e/api_validation_test.go, test/e2e/plain_provisioner_test.go, tools/imageregistry/bundle_local_image.yaml
In order to ensure that we can introduce a `ProvisionerClass` API in the
future without causing breaking changes in the `Bundle` and
`BundleDeployment` APIs, we need to ensure that `Bundle` and
`BundleDeployment` objects use provisioner class name values that can
reference the `metadata.name` field of potential `ProvisionerClass`
objects. Currently, the provisioner class names use both `.` and `/`
characters, which are invalid in certain core Kubernetes resource names.
Therefore, this commit changes the plain and registry provisioner IDs to
`core-rukpak-io-plain` and `core-rukpak-io-registry` and it changes the
validation of the `Bundle` and `BundleDeployment` provisioner class name
fields to ensure only DNS-1123 label names can be used.
This follows up on #487 and #479
Signed-off-by: Joe …
=> Provisioner class names must be DNS 1123 labels

Makefile, test/e2e/rukpakctl_test.go
- support both linux and local binary builds in the same make invocation
- fix e2e to use local rukpakctl binary
This should resolve the issue in the e2e run that occurred in #491 
Closes #489 
Closes #491
=> fix: e2e rukpakctl on mac

internal/source/image.go, internal/util/util.go, manifests/apis/crds/kustomization.yml, manifests/apis/crds/patches/bundle_validation.yaml, manifests/apis/crds/patches/bundledeployment_validation.yaml, test/e2e/api_validation_test.go, test/e2e/plain_provisioner_test.go
This PR 
- limit the length of bundledeployment to 45
- limit the length of bundle to 52
- make the name to unpack pod same as the bundle name
- shorten the bundle name length to the bundledeployment name length + 7 letters
Closes #485
=> bundledeployment name length 45

internal/rukpakctl/portforward.go, internal/rukpakctl/upload.go
When the port forwarder fails, it results in the tar writer process
hanging indefinitely. This fixes the issue by ensuring the the writer is
closed by the time the upload process returns.
This also improves the reliability of the port forward setup by waiting
(if necessary) for a service endpoint to be available.
These are the improvements I discovered needed to be made while
working on #508
=> More upload source improvements

internal/provisioner/plain/controllers/bundle_controller.go, internal/provisioner/registry/controllers/bundle_controller.go, manifests/core/resources/cluster_role.yaml, manifests/core/resources/deployment.yaml
- Minor simplification of core RBAC rules (combine upload and bundle get permission)
- Stop logging at `-v=10` verbosity in the core kube-rbac-proxy. This snuck in accidentally in an earlier PR when it was set to 10 for development debugging.
=> minor touchup to core manifests

api/v1alpha1/bundledeployment_types.go, internal/provisioner/helm/controllers/bundledeployment_controller.go, internal/provisioner/plain/controllers/bundledeployment_controller.go
Closes #518 
This is related to #333 and #331, but I'm not sure it closes them. #333 seems to be about renaming the `HasValidBundle` type or at least considering how it aligns to the Bundle `Unpacked` phase/condition. #331 is more about how to represent BD state to handle pivoting situations and still have a UX that makes sense and is general enough to cover different provisioner implementations.
=> De-duplicate `HasValidBundle` and `InvalidBundleContent` condition types

internal/rukpakctl/run.go
=> fix: rukpakctl run ignores provisioner class options

.goreleaser.template.yml
When creating the recent release it was found that we didn't add a wait to the release instructions for the `goreleaser.template.yaml`.
Closes #537
=> fix: add a helm-provisioner wait to the .goreleaser.template.yml

internal/source/git.go, test/e2e/plain_provisioner_test.go
=> git source: resolve branches/tags to commit hashes

.github/workflows/go-apidiff.yaml
Introduces the go-apidiff action that's used throughout the major opreator-framework repositories.
Closes #54 
=> .github: Add the go-apidiff workflow

Dockerfile, go.mod, internal/source/image.go, manifests/apis/webhooks/resources/deployment.yaml, manifests/apis/webhooks/resources/namespace.yaml, manifests/core/resources/deployment.yaml, manifests/provisioners/helm/resources/deployment.yaml
This PR brings Pod Security Admission (PSA) standards to RukPak in the form of updating the Namespace manifest (in accordance with the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/)) and Deployments. 
> **Note**: The namespace is running in a `baseline` model; However, we eventually want this to be restricted. For the time being I've implemented everything in such a way that `restricted` would be satisfied if we switch over *except* that the unpacker pod is running as root currently. This is because we cannot guarantee, at least at the moment, that the container image that we are going to unpack does not run as root. We'll need to think up a solution for this either here or in the future.
=> feat: add PSA compliance

.github/workflows/stale.yaml
Adding a new action that will run on dispatch or the start of everyday from the official [GitHub stale action](https://github.com/marketplace/actions/close-stale-issues?version=v5.1.1) to find stale issues or PR's and mark them with a `lifecycle/stale` label. To clarify the configuration outlined in this PR:
- Become stale after 30 days.
- 30 days after becoming stale close automatically. (We can change this, but old PR's feel like a natural fit for closing automatically to me).
- Mark automatically closed PR's with `lifecycle/rotten`.
- Will remove the stale label (and reset the "stale timer") after any update to the PR.
- Ignore adding the `lifecycle/stale` label or closing if marked with `lifecycle/frozen`.
- Become stale after 60 days
- Never close.
- Will remove the stale label (and …
=> ci: add action to manage stale issues/pr's

.github/workflows/stale.yaml
Github rate limits their API and, since this action can do a large number of actions in a short span of time, it defaults to 30 actions in a single run. This is fine, but the only problem is that if several issues are stale it will not get to them. As a result, this commit updates the action to run twice daily which should help the issue.
Additionally, this commit removes a failing print step from the job.
=> ci(stale): update to run twice daily and remove failing print step"

go.mod, internal/source/image.go
This is another take on #555 that makes use of applyconfigurations and server-side apply to "apply or re-create" unpack pods.
This should solve problems that we're seeing with our existing diff comparisons where we do not handle mutations performed by unrelated webhooks.
This should be more resilient than a "hash the pod struct" approach, which is susceptible to hash changes when the Pod struct changes. This approach should theoretically not result in an unpack pod respin unless something in our apply configuration actually changed.
I tested this on a cluster that performs pod mutations and verified that Bundles are able to be successfully unpacked, and the controller does not continuously re-create the unpack pod.
Closes #560 
=> image source: use applyconfiguration with server-side apply

.github/workflows/stale.yaml
Right now the bot is having a hard time processing our backlog due to its size. By default, there are 30 operations allowed before it stops attempting to process things to avoid rate limiting. We can get around this by increasing the amount of operations allowed per run. This has more potential for rate limiting, but should be fine in off hours.
In addition to adding these changes, this commit sets the the action only run once per day and updates the messaging it leaves when marking issues/prs as stale.
- Should we consider moving to another bot to perform this work? It seems there are some natural limitations around this.
- The more we triage our issues, the less operations that will need to be performed.
Relates to #546
=> fix: update stale action to have more capacity to process items

internal/source/image.go
=> image source: avoid shadowing /bin with emptyDir mount

Makefile, test/e2e/image_repo.go, test/e2e/plain_provisioner_test.go, test/e2e/registry_provisioner_test.go
Adding some small changes to enable testing to be a bit more configurable. This will allow downstream consumers of Rukpak to specify what image registry that their test images are served from.
=> test(e2e): add ability to configure the image registry for test images

api/v1alpha1/bundle_types.go, api/v1alpha1/bundledeployment_types.go, manifests/apis/crds/core.rukpak.io_bundledeployments.yaml, manifests/apis/crds/core.rukpak.io_bundles.yaml
Add **provisioner** in the for bundle and bundledeployment print columns.
=> add provisioner in the print column

manifests/apis/webhooks/resources/deployment.yaml, manifests/core/resources/deployment.yaml, manifests/crdvalidator/05_deployment.yaml, manifests/provisioners/helm/resources/deployment.yaml
Closes #571
All the patches for the resources/requests are in the manifests/kustomize.yaml file.  The `vars` of the kustomize seems better way but it is [deprecated](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/vars/).
=> add resources/requests to containers

internal/provisioner/bundledeployment/bundledeployment.go, test/e2e/helm_provisioner_test.go
=> add items to dynamic watch in helm

.github/workflows/e2e.yaml, .github/workflows/go-apidiff.yaml, .github/workflows/release-e2e.yaml, .github/workflows/release.yaml, .github/workflows/sanity.yaml, .github/workflows/unit.yaml
Use the actions/setup-go v3 major version, which has support for configuring Go based on the version specified in the root go.mod file. This reduces the amount of changes needed to bump Go versions over time.
=> .github/workflows: Get Go version from root go.mod file

internal/provisioner/bundledeployment/bundledeployment.go
This ensures that metrics produced by controller runtime use a controller name that includes the provisioner ID, which is important in cases where there are multiple bundle deployment controllers running in the same manager pod. Without this, controller-runtime chooses `bundledeployment` for the controller name (which is derived from the `For` type).
=> Set bundle deployment controller name correctly

.golangci.yaml, internal/provisioner/bundledeployment/bundledeployment.go, internal/source/git.go, internal/source/http.go, internal/source/unpacker.go, internal/storage/http.go, internal/util/util.go, test/e2e/rukpakctl_test.go
Signed-off-by: Tony Jin <kavinjsir@gmail.com>
Introduce `gosec` lint checker
1. Some changes are made based on gosec report, are these updates good OR any suggestions?
2. Wondering if is necessary to exclude some in the configuration?
Resolve: https://github.com/operator-framework/rukpak/issues/533
=> style: introduce gosec linter

internal/source/common.go, internal/source/git.go, internal/source/http.go, internal/source/image.go, internal/source/local.go, internal/source/upload.go
Signed-off-by: Tony Jin <kavinjsir@gmail.com>
Fill the `message` field in the `bundle` status condition for the UnpackSuccessful reason.
Resolve: https://github.com/operator-framework/rukpak/issues/529
=> fix: fill message in bundle status

Makefile, test/e2e/api_validation_test.go, test/e2e/image_repo.go, test/e2e/webhook_test.go, test/tools/git/git.yaml, test/tools/git/setup_git.sh, test/tools/imageregistry/sniff.sh
Explicitly specify localhost for some containers, otherwise docker.io ends up being used as the default repository.
=> Fix e2e: Force localhost for some containers

test/tools/imageregistry/daemonset.yaml
Problem: The Kubernetes project is moving its images from the k8s.gcr.io registry to the registry.k8s.io registry and our project relies on one of the images being moved. More information can be found here: https://github.com/kubernetes/k8s.io/issues/4780
Solution: Update the referenced image to point to the same image hosted at the new registry.
=> Move to the new Kubernetes image repository

Makefile, README.md, test/tools/remotedebug/kind-config.yaml, test/tools/remotedebug/kustomization.yaml, test/tools/remotedebug/patch/install_dlv_init.yaml, test/tools/remotedebug/patch/remote_debug_command.yaml, test/tools/remotedebug/resources/service.yaml
Adds `debug` make target to rukpak. The `debug` target is essentially the same as the `run` target except that, once finished, it exposes a local port to allow for remote debugging in the rukpak `core` container. This is done with the following:
* kind config to establish nodePort mapping
* deployment patches which:
* add an initContainer to install `dlv`
* prepend the `core` container command and args to run with dlv
* a service to link the `dlv` listener to the exposed nodePort
README is also updated to document the `debug` target and provides example launch config for vscode debugging.
=> Remote debug make target

test/tools/git/Dockerfile
I noticed that running `make e2e` locally on my Mac M1 machine would always fail the git+ssh source test because `alpine:3.4` is not a multi-arch image, so there were no runnable images for my machine (I need linux/arm64).
In this PR, I bump the git Dockerfile to use `alpine:3`, which _does_ have an arm64 image. I also simplify other aspects of the Makefile and remove unnecessary comment lines.
=> fix: use multi-arch alpine image for git test server

.github/workflows/e2e.yaml, .github/workflows/go-apidiff.yaml, .github/workflows/release-e2e.yaml, .github/workflows/release.yaml, .github/workflows/sanity.yaml, .github/workflows/stale.yaml, .github/workflows/todo.yaml, .github/workflows/unit.yaml
Updates our github actions to bring the in-line with operator-controller and silence deprecation warnings.
Also fixes the `go-apidiff` action.
=> Rukpak Actions Updates

.goreleaser.template.yml, Makefile, cmd/core/main.go, cmd/helm/main.go, cmd/rukpakctl/cmd/root.go, cmd/rukpakctl/cmd/version.go, cmd/unpack/main.go, cmd/webhooks/main.go, internal/version/version.go
@everettraven Gave me some inspiration in operator-framework/catalogd#46 to simplify rukpak's version handling/printing.
=> version: use go1.18+ embedded build info

docs/provisioners/plain.md
The link to plain bundle spec was incorrect in plain provisioner documentation.
=> Fix a link to plain bundle spec.

internal/crd/crd.go
Don't swallow the not-found error because doing so leads the following check to see if it's a not-found error to always fail.
=> Don't swallow the not-found error

Makefile, internal/util/defaults.go, manifests/apis/webhooks/resources/deployment.yaml, manifests/core/resources/deployment.yaml, manifests/crdvalidator/05_deployment.yaml, manifests/provisioners/helm/resources/deployment.yaml
The default tag for unpack image is currently "latest". Based on the recently built images in quay:
https://quay.io/repository/operator-framework/rukpak?tab=tags it looks like the "latest" tag does not exist. Instead "main" is used. This PR fixes the same.
=> [fix] Fix tag of default unpack image

Makefile
In #631 I added an optional `GOLANGCI_LINT_ARGS` into `make lint`, but... When you run `make lint` you get this:
```
ERRO Running error: context loading failed: failed to load packages: package .: no go files to analyze
```
This should fix it.
Example runs:
```
make lint
make lint GOLANGCI_LINT_ARGS="--verbose"
make lint GOLANGCI_LINT_ARGS="--out-format github-actions"
```
=> Fixes `make lint` when run without args

.github/workflows/sanity.yaml, .markdownlint.yaml
We use super-linter only to lint markdown files. New GitHub Action uses the smaeUnderlying linter (markdownlint), but it provides better output support: PRs get annotations from CI jobs when there is an linting issue.
Also this action is much faster then super-linter: at the moment of writing it takes 4-6 seconds when super-linter slim image takes 90-110 seconds.
=> Replaces super linter with markdown linter

.golangci.yaml
To enforce common patterns such as importing `k8s.io/api/rbac/v1` as `rbacv1`.
=> Adds importas rules

.golangci.yaml, internal/storage/http_test.go, internal/storage/storage_test.go, test/e2e/crdvalidator_test.go, test/e2e/e2e_suite_test.go, test/e2e/helm_provisioner_test.go, test/e2e/plain_provisioner_test.go, test/e2e/registry_provisioner_test.go, test/e2e/rukpakctl_test.go, test/e2e/webhook_test.go
Includes #635 which needs to be merged first
---
Linter which checks for common ginkgo issues like wrong error assertions (`Expect(err).To(BeNil())` instead of `Expect(err).NotTo(HaveOccurred())`), etc.
It also identifies `Expect` calls without a matcher. For example, we have 3 such instances in this repo:
```
test/e2e/rukpakctl_test.go:243:4       ginkgolinter  ginkgo-linter: "Expect": missing assertion method. Expected "Should()", "To()", "ShouldNot()", "ToNot()" or "NotTo()"
internal/storage/storage_test.go:64:3  ginkgolinter  ginkgo-linter: "Expect": missing assertion method. Expected "Should()", "To()", "ShouldNot()", "ToNot()" or "NotTo()"
internal/storage/storage_test.go:69:3  ginkgolinter  ginkgo-linter: "Expect": missing assertion method. Expected "Should()", "To()", …
```
=> Adds `ginkgolinter`

.github/workflows/manifests.yaml
Example test PR which fails this step:
https://github.com/operator-framework/rukpak/actions/runs/5284578866/jobs/9562154203?pr=641
Currently the action is not set as required so it depends on engineers paying attention to it. If the action is failing for an intentional change that should be noted in the PR's description.
=> Adding manifests verification step for PRs

.gitignore, Tiltfile, tilt.md
TODOs (either for this PR or as follow-ups)
=> Add initial Tilt support

internal/controllers/bundledeployment/bundledeployment.go, internal/controllers/bundledeployment/bundledeployment_test.go
This PR fixes an issue where helm's postrenderer
used to override the user defined object labels instead of merging them.
=> Fix: Overriding user defined labels

go.mod, go.sum
This bump brings a significant optimization for tarfs's backed by `io.Reader`s that also implement `io.ReaderAt`. In these cases, go-tarfs will not read all tar files into memory. Instead it will use the backing `io.ReaderAt` to open sections of the underlying tar as necessary.
For the most part, I think our code does _not_ pass in `io.ReaderAt` implementations because we have to pass things through a `gzip.Reader`.
=> bump go-tarfs from 1.1.0 to 1.2.1

.github/workflows/go-apidiff.yaml
go-apidiff is informational and can only be used effectively in the context of a comparison between two different commits. There is also no need to run it in the merge queue because it will not block merging any (as it is not required to pass in branch protection settings)
Removing non-PR triggers for go-apidiff.
=> GHA: only run go-apidiff for PRs

cmd/webhooks/main.go
Reintroduces the version flag to the webhook binary which was accidentally removed in Pull Request #754.
=> Reintroduce webhook version flag

.golangci.yaml, cmd/core/main.go, cmd/helm/main.go, internal/controllers/bundledeployment/bundledeployment.go, internal/controllers/bundledeployment/bundledeployment_test.go, internal/convert/registryv1.go, internal/convert/registryv1_test.go, internal/storage/http_test.go, internal/storage/localdir_test.go, internal/storage/storage_test.go, test/e2e/api_validation_test.go, test/e2e/crdvalidator_test.go, test/e2e/e2e_suite_test.go, test/e2e/helm_provisioner_test.go, test/e2e/plain_provisioner_test.go, test/e2e/registry_provisioner_test.go, test/e2e/webhook_test.go
Adds linter grouping to match [configuration](https://github.com/operator-framework/operator-controller/pull/748) in operator-controller.
I did add dot grouping to rukpak since there are several dot imports in the test files for ginkgo and gomega. However, the revive linter does complain about the dot imports.
=> Import groups linting

.goreleaser.yml, Makefile
=> Makefile: avoid re-evaluating vars unnecessarily; other minor fixup

pkg/source/image.go
This PR adds the go test coverage variable to the
unpack pod. It also creates necessary volumes
if the GOCOVERDIR env var is set.
=> :sparkles: [Add] Coverage dir for unpack pod

Makefile
- explicitly configure shell
- change CONTAINER_RUNTIME error to warning
- fix broken GORELEASER_ARGS setup
=> Makefile: various fixes

pkg/convert/registryv1.go
Will result in this message:
> supported install modes [MultiNamespace OwnNamespace SingleNamespace] do not support target all namespaces
Instead of this when targeting all namespaces:
> supported install modes [OwnNamespace SingleNamespace MultiNamespace] do not support target namespaces []
=> Improve error message for all namespaces

cmd/core/main.go, cmd/helm/main.go, internal/controllers/bundledeployment/bundledeployment.go, pkg/handler/interfaces.go
This would help in removing the duplicate handler
interface implmentation in operator-controller.
=> externalize handler interface implementation

pkg/convert/registryv1_test.go
Currently we do not allow:
* Bundles with webhook definitions
* Bundles which provide API Service definitions
=> Add tests to make sure rukpak enforces limitations

api/v1alpha2/bundle_types.go, cmd/core/main.go, cmd/helm/main.go, manifests/base/apis/crds/core.rukpak.io_bundledeployments.yaml, pkg/source/image_registry.go, pkg/source/unpacker.go, test/e2e/registry_provisioner_test.go, test/tools/imageregistry/image-registry-secure.sh, test/tools/imageregistry/image-registry.sh
Remove `rootCAs` from the `NewDefaultUnpacker` API, the argument is no longer used for HTTP transport.
Add `CertificateData` to the ImageSource struct. This is PEM-encoded data (straight from a Secret[tls.crt]) to be used to validate the certificate used to access an image regidstry (works along side the `InsecureSkipTLSVerify` option).
=> Update certificate support
