operator-framework/rukpak

- .gitignore
- README.md
Signed-off-by: Daniel Sover <dsover@redhat.com>
> update README to include latest APIs

- provisioner/registryv1/controllers/bundleinstance_controller.go
Update the registryv1's BundleInstance controller and reset the
status.InstalledBundleName when the corresponding spec.BundleName does
not exist.
This is easy to produce locally:
- Create a Bundle
- Create a BundleInstance that specifies the previously created Bundle
- Delete the Bundle
- Ensure the BundleInstance's status.InstalledBundleName doesn't get reset
> registryv1: Reset the InstalledBundle status field when the Bundle doesn't exist

- test/e2e/k8s_provisioner_test.go
The k8s provisioner currently maintains a Bundle unpack Pod, and parses the Pod's logs in order to read unpacked Bundle contents so it can store it in a series of ConfigMaps. We should ensure we a simple e2e test to ensure this behavior so we're not regressing silently.
> e2e: Ensure the underlying Bundle unpack Pod is re-created when deleted

- internal/util/util.go
- test/e2e/e2e_suite_test.go
- test/e2e/plain-v0_provisioner_test.go
> e2e: Ensure the Bundle's metadata ConfigMap gets re-created

- .github/workflows/todo.yaml
> ci: Add a workflow for creating issues from TODO comments

- provisioner/plain-v0/controllers/bundle_controller.go
- test/e2e/plain-v0_provisioner_test.go
> fix: update unpack pod name to start with plain-v0

- internal/util/util.go
- provisioner/plain-v0/controllers/bundle_controller.go
- provisioner/plain-v0/controllers/bundleinstance_controller.go
Move the provisioner-related Bundle/BI filtering methods from the
plain+v0 provisioner codebase to the root internal/ directory so they
can be re-used for other provisioner implementations.
> internal,provisioner: Add provisioner filtering functions

- test/e2e/plain-v0_provisioner_test.go
Adding a e2e test case for creating two BundleInstances that reference the same Bundle. In this particular case we are simulating and expecting a InstallFailed status with a Message of that references the duplicated resources. 
1. Is there a situation where we want to have multiple BundleInstances reference the same Bundle? If so, how do we get around this test in the future?
2. Is this a valid way of checking this behavior?
> test(e2e): add test case for two bi's with duplicate resources

- README.md
Revamps the top-level README and removes references to the ProvisionerClass API which has not yet been implemented.
> doc: cleanup root level README from stale documentation

- test/e2e/plain-v0_provisioner_test.go
> test(e2e): add eventually handler around creation multiple bundle-instances

- CONTRIBUTING.md
- README.md
> doc: add contributing doc

- internal/updater/updater_test.go
Making suggested changes for readabilities and some improvements. https://github.com/operator-framework/rukpak/pull/111
> cleanup and improve readabilities of updater unit tests

- .github/workflows/e2e.yaml
> Upgrade kind to 0.12 (k8s to 1.23) for e2e

- Makefile
- go.mod
- hack/tools/go.mod
- hack/tools/go.sum
- hack/tools/tools.go
- internal/updater/updater_suite_test.go
- internal/updater/updater_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/plain_provisioner_test.go
> bump ginkgo to v2

- docs/plain-bundle-spec.md
> docs: Enable the commands to be copy-pasted locally

- Makefile
Move around the Makefile e2e target to the "testing" section so it's correctly placed when running `make help` locally.
Before:
```console
$ make help
...
build/load:
build-container  Builds provisioner container image locally
kind-load        Load-image loads the currently constructed image onto the cluster
kind-cluster     Standup a kind cluster for e2e testing usage
e2e              Run e2e tests against a kind cluster
...
```
After:
```console
$ make help
...
testing:
test             Run the tests
test-unit        Run the unit tests
test-e2e         Run the e2e tests
e2e              Run e2e tests against a kind cluster
kind-cluster     Standup a kind cluster for e2e testing usage
...
```
> Makefile: Fix the help target output by moving to the e2e target to testing section

- test/e2e/plain_provisioner_test.go
This PR updates the duplicate BI e2e test to ensure that the original BI is always the owner of the provided Bundle, to prevent any flakes where the duplicate bundle ends up owning the Bundle before the original.
Closes #200
> e2e: fix duplicate BI e2e test flake

- test/e2e/plain_provisioner_test.go
> make deletion test cleanups deterministic

- Makefile
> Makefile: remove -v from ginkgo run

- test/e2e/e2e_suite_test.go
- test/e2e/plain_provisioner_test.go
> e2e: Ensure that CRDs can be transistioned during BundleInstance pivots

- test/e2e/plain_provisioner_test.go
> fix: refactor git bundles e2e test

- docs/git-bundles.md
- docs/plain-bundle-spec.md
> (docs): add documentation and examples around git-based bundles

- test/e2e/plain_provisioner_test.go
Adds an e2e test to ensure that git-based bundles with custom directories work as expected. Closes #233.
> (e2e): verify a specified git bundle directory root works

- .goreleaser.template.yml
Signed-off-by: Tyler Slaton <tyslaton@redhat.com>
Closes #53
> ci: add support for multi-architecture releases

- Makefile
The install section of the Makefile is currently pretty confusing and this PR attemps to streamline it, as well as removing the duplicate calls to `cert-manager` that are currently occurring. That being said, there are some other issues in the 0.3 milestone (#187 and #209) that address the Makefile as well so this PR could potentially not be necessary after those go through.
> Remove the duplicate cert-manager commands; remove install/deploy directives

- Makefile
> tidy hack/tools module in "make tidy" target

- internal/provisioner/plain/controllers/bundle_controller.go
- internal/provisioner/plain/controllers/bundleinstance_controller.go
- internal/provisioner/plain/main.go
- internal/storage/storage.go
- internal/util/labels.go
- internal/util/util.go
> Refactor rukpak owner labels into constants

- api/v1alpha1/bundle_webhook.go
- test/e2e/plain_provisioner_test.go
> bundle webhook: enforce spec immutability

- test/e2e/plain_provisioner_test.go
> e2e: Avoid hardcoding status condition state

- test/e2e/plain_provisioner_test.go
> e2e: Refactor status condition checks to use gomega matchers

- CONTRIBUTING.md
- README.md
> Add quickstart section to root-level README

- internal/provisioner/plain/README.md
> plain: Fix the printer columns in the README.md

- README.md
> README: Fix markdown linting violation

- README.md
> README: Re-organize top-level headers

- docs/git-bundles.md
- docs/plain-bundle-spec.md
Add private image registry and private git repository support in docs
Closes #324
> add private git repository / private image registry support docs

- README.md
Signed-off-by: Tyler Slaton <tyslaton@redhat.com>
> docs: add note about spin-up time to README

- README.md
- internal/provisioner/plain/README.md
Adds a warning message to the BI section indicating that anyone who can create a BI can gain cluster-admin privileges.
> Add warning message regarding BundleInstances

- docs/release.md
> docs: Add documentation for cutting new rukpak releases

- internal/provisioner/plain/controllers/bundleinstance_controller.go
- test/e2e/plain_provisioner_test.go
This is a variation of the solution in #329, but with improvements in the controller rather than extra checks in the test.
> wrap various errors related to missing APIs that are required to install bundles

- Makefile
Move the release/quickstart Makefile targets outside of the hack/tools section, and into their own section. Update both of those targets and add a comment that surfaces when `make help` is run.
> Makefile: Surface release related targets in help output

- Makefile
> Makefile: Fix the quickstart release manifest generation target

- docs/plain-bundle-spec.md
> doc: add putting imagePullSecret in the service account

- .github/workflows/e2e.yaml
- Makefile
- hack/tools/go.mod
- hack/tools/go.sum
- hack/tools/tools.go
Attempts to fix open comments left on [PR#375](https://github.com/operator-framework/rukpak/pull/375) after merge.
> Addresses Open Issues with Commit #375

- Makefile
- cmd/rukpakctl/cmd/root.go
- cmd/rukpakctl/cmd/unpack.go
- cmd/rukpakctl/main.go
Closes #369 
This has just scaffolding for the rukpakctl.  Are there anything to be added in this PR?
> rukpakctl scaffolding

- test/e2e/plain_provisioner_test.go
> e2e: Add a test that ensures Bundles referencing the wrong provisioner ID don't get unpacked

- test/e2e/registry_provisioner_test.go
> fix e2e test

- test/e2e/e2e_suite_test.go
- test/e2e/plain_provisioner_test.go
> add plain provisioner http server test

- test/e2e/plain_provisioner_test.go
> add 2 more local source e2e tests

- README.md
> docs: Add CI status badge to root README

- README.md
- docs/release.md
> addresses markdown issues raised by linter

- internal/rukpakctl/upload.go
> rukpactl run: cancel context in event of an upload error

- test/e2e/rukpakctl_test.go
> rukpakctl test

- docs/provisioner-spec.md
Quick fix of the provisioner-spec
> minor provisioner spec fix

- internal/provisioner/helm/README.md
Minors helm provisioner README changes: https -> http
> helm provisioner README minor changes

- Makefile
Update the Makefile and use a variable for the kubectl executable to avoid hardcoding it's path. This mirrors the existing pattern used for the container runtime used throughout the Makefile targets. This is beneficial when the kubectl executable in my $PATH is out-of-date and I need to override the executable path used.
> Makefile: Add support for overriding the kubectl executable

- internal/provisioner/helm/controllers/bundle_controller.go
> add pod watch to helm provisioner bundle controller

- api/v1alpha1/bundledeployment_types.go
- internal/provisioner/helm/controllers/bundledeployment_controller.go
- internal/provisioner/plain/controllers/bundledeployment_controller.go
- internal/updater/bundle-deployment/updater.go
- manifests/apis/crds/core.rukpak.io_bundledeployments.yaml
> add status.observedGeneration in BD

- docs/sources/http.md
> adding http source doc

- internal/source/git.go
- test/e2e/helm_provisioner_test.go
Closes #540 
There are some change and addition to the custom FSes.
Adding DirRead to BaseDirFS
Add Close for billyFS
Change not to fail Open for a  directory for billyFS
> fix second helm bundle format handle error

- Makefile
- internal/convert/registryv1.go
- test/e2e/registry_provisioner_test.go
- testdata/bundles/registry/invalid/Dockerfile
- testdata/bundles/registry/invalid/manifests/update-service-operator.clusterserviceversion.yaml
- testdata/bundles/registry/invalid/metadata/annotations.yaml
> *: Enforce that the AllNamespace install mode has been enabled

- internal/util/util.go
> silence noisy and unnecessarily alarming logging in watch handler

- Makefile
> chore: bump cert-mgr version

- .goreleaser.template.yml
- Makefile
- cmd/core/main.go
- cmd/helm/main.go
- cmd/rukpakctl/cmd/alpha_bootstrap.go
- cmd/rukpakctl/cmd/bundle.go
- cmd/rukpakctl/cmd/bundledeployment.go
- cmd/rukpakctl/cmd/content.go
- cmd/rukpakctl/cmd/run.go
- cmd/webhooks/main.go
- internal/util/defaults_upstream.go
- test/e2e/plain_provisioner_test.go
Also, start using build tags to make it easier to change defaults for downstream builds.
> define constants for common defaults

- README.md
> docs: update README.md links to reference the correct locations

- internal/convert/registryv1.go
> internal/convert: Fix 'webhookDefiniions' typo in error message

- .github/workflows/unit.yaml
- Makefile
Equivalent of https://github.com/operator-framework/operator-controller/pull/279
> Adds codecov integration
